import type { Evergreen } from "./slides";

/** Non-IPO-day content bank: investing + personal finance, beginner ↔ expert. */
export const EVERGREEN: Evergreen[] = [
  {
    id: "gmp-truth",
    level: "beginner",
    pillar: "IPO sense",
    cover: "GMP is a rumour, not a result",
    sub: "What grey market premium actually tells you",
    points: [
      "GMP = what strangers will pay before listing. Unofficial, unregulated.",
      "It predicts direction ~70% of the time — magnitude, far less.",
      "Skyways showed +23% GMP and listed −10%. Receipts matter.",
      "Bet sizing rule: GMP sizes curiosity, QIB sizes conviction.",
    ],
    cta: "Before your next IPO, check QIB Day-1 first — then glance at GMP.",
  },
  {
    id: "qib-rule",
    level: "beginner",
    pillar: "IPO sense",
    cover: "QIB Day-1 tells you everything",
    sub: "The one number to watch in any IPO",
    points: [
      "QIB = banks, MFs, insurers bidding with research teams.",
      "Strong QIB by Day 2 → real demand. Weak QIB → listing pop usually dies.",
      "Retail oversubscription alone means hype, not quality.",
      "Our rule: no apply-for-listing unless QIB crosses 5x by Day 2.",
    ],
    cta: "Save this for the next IPO window — check QIB before you check GMP.",
  },
  {
    id: "fresh-vs-ofs",
    level: "beginner",
    pillar: "IPO sense",
    cover: "Fresh issue vs OFS",
    sub: "Are you funding growth or the exit?",
    points: [
      "Fresh issue = money goes INTO the company (plants, debt, R&D).",
      "OFS = money goes to existing shareholders cashing out.",
      "Mostly-OFS IPOs can still pop — but ask what you're buying into.",
      "Green flag: 60%+ fresh capital funding real expansion.",
    ],
    cta: "Next DRHP you open, find 'Objects of the Issue' first. Takes 2 minutes.",
  },
  {
    id: "allotment-math",
    level: "beginner",
    pillar: "IPO sense",
    cover: "Oversubscribed? It's a lottery",
    sub: "How retail allotment actually works",
    points: [
      "If retail is oversubscribed, allotment is a computerised lottery by lot.",
      "Applying for 10 lots does NOT raise retail odds — one PAN, one lottery ticket per lot slab.",
      "Big applications only help in the HNI (NII) bucket — different game.",
      "So: apply 1 lot in every family account instead of 5 in yours.",
    ],
    cta: "Tag someone who applies 10 lots in one account.",
  },
  {
    id: "listing-playbook",
    level: "beginner",
    pillar: "IPO sense",
    cover: "Listing day: have a plan before 10am",
    sub: "Three scenarios, three responses",
    points: [
      "Opens +40% up → book half, trail the rest at cost.",
      "Opens flat ±5% → hold only if the business is a real compounder.",
      "Opens at discount → never average down on Day 1. Let it settle.",
      "Decide the night before. Pre-open emotions are expensive.",
    ],
    cta: "Screenshot this before your next listing day.",
  },
  {
    id: "cfo-vs-pat",
    level: "expert",
    pillar: "Forensics",
    cover: "Profit is an opinion. Cash is a fact",
    sub: "The CFO-vs-PAT test in 30 seconds",
    points: [
      "PAT can be booked. Operating cash flow has to arrive in the bank.",
      "CFO/PAT below 0.5 for years = profits aren't converting. Red flag.",
      "Above ~0.9 consistently = quality earnings. Trust the compounder.",
      "Find it in the cash-flow statement of any RHP in 2 minutes.",
    ],
    cta: "Pull up any recent IPO filing and run the ratio. Comment what you find.",
  },
  {
    id: "anchor-meaning",
    level: "expert",
    pillar: "Forensics",
    cover: "Anchors aren't decoration",
    sub: "Reading the anchor book like a pro",
    points: [
      "Anchors buy a day before open at a fixed price — with a 30-day lock-in.",
      "30%+ anchored by quality MFs = institutional confidence, real signal.",
      "Unknown names + tiny anchor book = nobody serious wanted early entry.",
      "Check WHO anchored, not just how much.",
    ],
    cta: "Next IPO, google the anchor list before you apply. 5 minutes, big edge.",
  },
  {
    id: "promoter-skin",
    level: "expert",
    pillar: "Forensics",
    cover: "Follow the promoter's wallet",
    sub: "Skin in the game, quantified",
    points: [
      "Promoter holding 70%+ post-IPO = incentives aligned with you.",
      "Dropping below 50% via a giant OFS = you're buying their exit.",
      "Watch pre-IPO placements: cheap shares to insiders months before = dilution warning.",
      "Related-party revenue above 20%? You're funding the family ecosystem.",
    ],
    cta: "Open any DRHP's 'Capital Structure' page and check these three numbers.",
  },
  {
    id: "pe-trap",
    level: "expert",
    pillar: "Valuation",
    cover: "A low P/E can still be expensive",
    sub: "Valuation vs peers, not in isolation",
    points: [
      "IPO P/E of 25 means nothing until you line up 3 listed peers.",
      "Paying 40% over peers needs 40%-better growth. Usually absent.",
      "Check EV/EBITDA too — debt hides in P/E's blind spot.",
      "Our dossiers always show the peer table first for this reason.",
    ],
    cta: "Compare any live IPO's P/E with its peers today. Post the gap below.",
  },
  {
    id: "compounding-math",
    level: "beginner",
    pillar: "Money basics",
    cover: "₹10k/month beats timing the market",
    sub: "The only math that matters",
    points: [
      "₹10,000/month at 12% for 15 years ≈ ₹50 lakh. Invested: ₹18 lakh.",
      "Starting 5 years late costs more than any crash ever will.",
      "IPOs are spice. SIPs are the meal. Get the order right.",
      "Automate it, then forget the password (almost).",
    ],
    cta: "Share this with someone who says 'I'll start investing when…'",
  },
  {
    id: "emergency-first",
    level: "beginner",
    pillar: "Money basics",
    cover: "Before your first IPO: 6 months of expenses",
    sub: "The unsexy prerequisite",
    points: [
      "Emergency fund = 6 months expenses in liquid fund or sweep-in FD.",
      "Why it matters: you never sell investments in panic.",
      "IPO allotment is blocked capital for ~10 days. Plan cash flow.",
      "No emergency fund + leveraged IPO bets = how accounts blow up.",
    ],
    cta: "Build the fund first. The IPOs will still be here.",
  },
  {
    id: "inflation-tax",
    level: "beginner",
    pillar: "Money basics",
    cover: "Your savings account loses 3% a year",
    sub: "Inflation is a silent portfolio killer",
    points: [
      "4% savings interest minus 6-7% inflation = negative real return.",
      "₹1 lakh today ≈ ₹54,000 of buying power in 10 years at 6%.",
      "Equities exist to beat inflation, not to make you rich overnight.",
      "Staying in cash feels safe. It is a guaranteed slow loss.",
    ],
    cta: "Save this the next time 'safe' feels smart.",
  },
  {
    id: "gmp-vs-qib",
    level: "beginner",
    pillar: "IPO sense",
    cover: "GMP vs QIB: which do you trust?",
    sub: "Sentiment against substance",
    points: [],
    cta: "From tomorrow: check QIB first, GMP second. In that order, always.",
    template: "duel",
    versus: {
      a: "GMP",
      aSub: "Grey-market chatter. Unofficial, swings by lunch, wrong on magnitude often.",
      b: "QIB",
      bSub: "Institutions bidding crores after reading the full filing. Locked-in conviction.",
      verdict: "GMP sizes curiosity. QIB sizes the bet.",
    },
  },
  {
    id: "sip-vs-ipo",
    level: "beginner",
    pillar: "Money basics",
    cover: "SIP vs IPO lump sum",
    sub: "Both have a seat — different chairs",
    points: [],
    cta: "Automate the SIP. Use IPOs for satellite bets, never the core.",
    template: "duel",
    versus: {
      a: "Monthly SIP",
      aSub: "Boring, automatic, compounds for decades. The meal.",
      b: "IPO bets",
      bSub: "Exciting, lumpy, needs research per issue. The spice.",
      verdict: "Meal first, spice second. Never the reverse.",
    },
  },
  {
    id: "ledger-proof",
    level: "beginner",
    pillar: "IPO sense",
    cover: "We audit our own signal",
    sub: "GMP predictions vs actual listings, on record",
    points: [
      "Direction right most of the time — magnitude overstated by ~15-20 points.",
      "Skyways: +23% GMP chatter, −10% listing. Filed under: traps.",
      "Tempsens: triple-digit pop the tape actually caught.",
    ],
    cta: "Follow for the only GMP tracker that shows its misses too.",
    template: "stat",
    stat: { big: "~70%", small: "of the time GMP gets the listing DIRECTION right. Magnitude? That's where traders get humbled." },
  },
  {
    id: "hundred-x",
    level: "expert",
    pillar: "IPO sense",
    cover: "What 100x subscription really means",
    sub: "Your allotment odds, decoded",
    points: [
      "100x retail = roughly a 1-in-100 lottery per lot. Celebrities lose these daily.",
      "Oversubscription measures hype distribution, not company quality.",
      "Smart money watches WHERE the bids are (QIB), not how many.",
    ],
    cta: "Stop chasing the most-subscribed IPO. Chase the best-subscribed-by-QIB one.",
    template: "stat",
    stat: { big: "1:100", small: "Your rough retail allotment odds in a 100x-subscribed IPO. One PAN, one lottery ticket." },
  },
  {
    id: "pre-apply-checklist",
    level: "beginner",
    pillar: "IPO sense",
    cover: "5 ticks before any IPO",
    sub: "The pre-apply checklist",
    points: [
      "QIB above 5x by Day 2? If not, stop here.",
      "Fresh issue above 50%? Growth, not exit.",
      "CFO/PAT above 0.8? Profits that actually arrive.",
      "Promoter holding 60%+ post-listing? Aligned.",
      "Priced near peers, not 40% above them?",
    ],
    cta: "Screenshot this. Run it on the next IPO that opens.",
    template: "checklist",
  },
  {
    id: "cutoff-checklist",
    level: "beginner",
    pillar: "IPO sense",
    cover: "Retail's tiny superpowers",
    sub: "Cut-off, UPI timing, family accounts",
    points: [
      "Always bid at cut-off price — retail's reserved right, guarantees validity.",
      "Approve the UPI mandate before 5pm on close day or the bid dies.",
      "One lot per family PAN beats five lots in one PAN (lottery math).",
      "Keep the blocked amount liquid — it unblocks in ~10 days either way.",
    ],
    cta: "Send this to the family group before the next IPO week.",
    template: "checklist",
  },
  {
    id: "ipo-10-days",
    level: "beginner",
    pillar: "IPO sense",
    cover: "An IPO's 10 days",
    sub: "Open to listing, end to end",
    points: [
      "Day 1-3: bidding window. Watch QIB converge, ignore Day-1 retail noise.",
      "Day 4-5: allotment lottery runs. Check registrar with PAN.",
      "Day 6: shares credit to demat (or funds unblock).",
      "Day 7+: listing at 10am. Your pre-written plan executes — no improvising.",
    ],
    cta: "Save this timeline. You'll reuse it every single IPO.",
    template: "timeline",
  },
  {
    id: "allotment-journey",
    level: "beginner",
    pillar: "IPO sense",
    cover: "Where your money sleeps",
    sub: "The ASBA trail, demystified",
    points: [
      "You bid: money is BLOCKED, not debited. It earns savings interest meanwhile.",
      "Oversubscribed retail: computerised lottery decides your lot.",
      "Allotted: exact amount debited, shares hit demat before listing.",
      "Not allotted: full unblock, usually within a day. Zero loss, zero gain.",
    ],
    cta: "ASBA means you never pay for shares you don't get. That's the whole trick.",
    template: "timeline",
  },
  {
    id: "big-sub-myth",
    level: "beginner",
    pillar: "IPO sense",
    cover: "Big subscription ≠ safe listing",
    sub: "The most expensive myth in IPOs",
    points: ["Myth filler", "Fact filler"],
    cta: "Hype fills applications. Only diligence fills portfolios.",
    template: "mythfact",
    mythfact: {
      myth: "200x subscribed, so listing gains are guaranteed.",
      fact: "Subscription measures crowd heat. Listings answer to anchors, market mood and valuation — crowds are wrong at tops.",
    },
  },
  {
    id: "gmp-guarantee-myth",
    level: "beginner",
    pillar: "IPO sense",
    cover: "GMP is not a price lock",
    sub: "Read it right or pay for it",
    points: ["Myth filler", "Fact filler"],
    cta: "Treat GMP as weather, QIB as climate. Dress accordingly.",
    template: "mythfact",
    mythfact: { myth: "GMP of ₹300 means I make ₹300 per share.", fact: "GMP is an unofficial quote that can halve overnight. Our ledger shows magnitude missed by ~20 points routinely." },
  },
];

export function getEvergreen(id: string) {
  return EVERGREEN.find((e) => e.id === id);
}
